

sass:
  sass_dir: assets/css

# plugins:
#   - jekyll-autoprefixer


title: "Jekyll Boostrap-4" # the name of your site, e.g. ACME Corp.
tagline: "An awesome tagline"

description: >- # this means to ignore newlines until "baseurl:"

url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
google_analytics: UA-111111111-1
twitter:
  username:
  card: summary #keep this to generate a twitter share card



collections:
  pages:
    output: true
    # permalink: /:path


defaults:
  - scope:
      type: pages
    values:
      layout: page
